import { createServer } from "miragejs"

let server = createServer();

server.get("/api/result", { result: [
  { id: 1, title: "title1",username: "@username1", image: 0 },
  { id: 2, title: "title2",username: "@username2", image: 1 },
  { id: 3, title: "title3",username: "@username3", image: 2 },
  { id: 4, title: "title4",username: "@username4", image: 0 },
  { id: 5, title: "title5",username: "@username5", image: 1 },
  { id: 6, title: "title6",username: "@username6", image: 2 },
  { id: 7, title: "title7",username: "@username7", image: 0 },
  { id: 8, title: "title8",username: "@username8", image: 1 },
  { id: 9, title: "title9",username: "@username9", image: 2 },
  { id: 10, title: "title10",username: "@username10", image: 0 },
  { id: 11, title: "title11",username: "@username11", image: 0 },
  { id: 12, title: "title12",username: "@username12", image: 1 },
  { id: 13, title: "title13",username: "@username13", image: 2 },
  { id: 14, title: "title14",username: "@username14", image: 0 },
  { id: 15, title: "title15",username: "@username15", image: 1 },
  { id: 16, title: "title16",username: "@username16", image: 2 },
  { id: 17, title: "title17",username: "@username17", image: 0 },
  { id: 18, title: "title18",username: "@username18", image: 1 },
  { id: 19, title: "title19",username: "@username19", image: 2 },
  { id: 20, title: "title20",username: "@username20", image: 0 },
  { id: 21, title: "title21",username: "@username21", image: 0 },
  { id: 22, title: "title22",username: "@username22", image: 1 },
  { id: 23, title: "title23",username: "@username23", image: 2 },
  { id: 24, title: "title24",username: "@username24", image: 0 },
  { id: 25, title: "title25",username: "@username25", image: 1 },
  { id: 26, title: "title26",username: "@username26", image: 2 },
  { id: 27, title: "title27",username: "@username27", image: 0 },
  { id: 28, title: "title28",username: "@username28", image: 1 },
  { id: 29, title: "title29",username: "@username29", image: 2 },
  { id: 30, title: "title30",username: "@username30", image: 0 },
  { id: 31, title: "title31",username: "@username31", image: 0 },
  { id: 32, title: "title32",username: "@username32", image: 1 },
  { id: 33, title: "title33",username: "@username33", image: 2 },
  { id: 34, title: "title34",username: "@username34", image: 0 },
  { id: 35, title: "title35",username: "@username35", image: 1 },
  { id: 36, title: "title36",username: "@username36", image: 2 },
  { id: 37, title: "title37",username: "@username37", image: 0 },
  { id: 38, title: "title38",username: "@username38", image: 1 },
  { id: 39, title: "title39",username: "@username39", image: 2 },
  { id: 40, title: "title40",username: "@username40", image: 0 },
  { id: 41, title: "title41",username: "@username41", image: 0 },
  { id: 42, title: "title42",username: "@username42", image: 1 },
  { id: 43, title: "title43",username: "@username43", image: 2 },
  { id: 44, title: "title44",username: "@username44", image: 0 },
  { id: 45, title: "title45",username: "@username45", image: 1 },
  { id: 46, title: "title46",username: "@username46", image: 2 },
  { id: 47, title: "title47",username: "@username47", image: 0 },
  { id: 48, title: "title48",username: "@username48", image: 1 },
  { id: 49, title: "title49",username: "@username49", image: 2 },
  { id: 50, title: "title50",username: "@username50", image: 0 },
]},{timing:2000})

server.get("/api/followers", { users: [
  { id: 1, fullname: "fullname1",username: "@username1",following: true, image: 0 },
  { id: 2, fullname: "fullname2",username: "@username2",following: false, image: 1 },
  { id: 3, fullname: "fullname3",username: "@username3",following: false, image: 2 },
  { id: 4, fullname: "fullname4",username: "@username4",following: true, image: 0 },
  { id: 5, fullname: "fullname5",username: "@username5",following: false, image: 1 },
  { id: 6, fullname: "fullname6",username: "@username6",following: true, image: 2 },
  { id: 7, fullname: "fullname7",username: "@username7",following: false, image: 0 },
  { id: 8, fullname: "fullname8",username: "@username8",following: true, image: 1 },
  { id: 9, fullname: "fullname9",username: "@username9",following: false, image: 2 },
  { id: 10, fullname: "fullname10",username: "@username10",following: true, image: 0 },
  { id: 11, fullname: "fullname11",username: "@username11",following: true, image: 0 },
  { id: 12, fullname: "fullname12",username: "@username12",following: false, image: 1 },
  { id: 13, fullname: "fullname13",username: "@username13",following: false, image: 2 },
  { id: 14, fullname: "fullname14",username: "@username14",following: true, image: 0 },
  { id: 15, fullname: "fullname15",username: "@username15",following: false, image: 1 },
  { id: 16, fullname: "fullname16",username: "@username16",following: true, image: 2 },
  { id: 17, fullname: "fullname17",username: "@username17",following: false, image: 0 },
  { id: 18, fullname: "fullname18",username: "@username18",following: true, image: 1 },
  { id: 19, fullname: "fullname19",username: "@username19",following: false, image: 2 },
  { id: 20, fullname: "fullname20",username: "@username20",following: true, image: 0 },

]},{timing:2000})
server.get("/api/following", { users: [
  { id: 1, fullname: "fullname1",username: "@username1", image: 0 },
  { id: 2, fullname: "fullname2",username: "@username2", image: 1 },
  { id: 3, fullname: "fullname3",username: "@username3", image: 2 },
  { id: 4, fullname: "fullname4",username: "@username4", image: 0 },
  { id: 5, fullname: "fullname5",username: "@username5", image: 1 },
  { id: 6, fullname: "fullname6",username: "@username6", image: 2 },
  { id: 7, fullname: "fullname7",username: "@username7", image: 0 },
  { id: 8, fullname: "fullname8",username: "@username8", image: 1 },
  { id: 9, fullname: "fullname9",username: "@username9", image: 2 },
  { id: 10, fullname: "fullname10",username: "@username10", image: 0 },
  { id: 11, fullname: "fullname11",username: "@username11", image: 0 },
  { id: 12, fullname: "fullname12",username: "@username12", image: 1 },
  { id: 13, fullname: "fullname13",username: "@username13", image: 2 },
  { id: 14, fullname: "fullname14",username: "@username14", image: 0 },
  { id: 15, fullname: "fullname15",username: "@username15", image: 1 },
  { id: 16, fullname: "fullname16",username: "@username16", image: 2 },
  { id: 17, fullname: "fullname17",username: "@username17", image: 0 },
  { id: 18, fullname: "fullname18",username: "@username18", image: 1 },
  { id: 19, fullname: "fullname19",username: "@username19", image: 2 },
  { id: 20, fullname: "fullname20",username: "@username20", image: 0 },
]},{timing:2000})

server.get("/api/tags", { result: [
  { id: 1, tags: "cool",result: 200 },
  { id: 2, tags: "verylongtaggggggggggggggggg",result: 201 },
  { id: 3, tags: "cool",result: 202 },
  { id: 4, tags: "cool",result: 203 },
  { id: 5, tags: "cool",result: 204 },
  { id: 6, tags: "cool",result: 205 },
  { id: 7, tags: "cool",result: 206 },
  { id: 8, tags: "cool",result: 207 },
  { id: 9, tags: "cool",result: 208 },
  { id: 10, tags: "cool",result: 209 },
  { id: 11, tags: "cool",result: 200 },
  { id: 12, tags: "verylongtaggggggggggggggggg",result: 201 },
  { id: 13, tags: "cool",result: 202 },
  { id: 14, tags: "cool",result: 203 },
  { id: 15, tags: "cool",result: 204 },
  { id: 16, tags: "cool",result: 205 },
  { id: 17, tags: "cool",result: 206 },
  { id: 18, tags: "cool",result: 207 },
  { id: 19, tags: "cool",result: 208 },
  { id: 20, tags: "cool",result: 209 },
  
]},{timing:2000})